export const schedule2 = {
"id":1,
"title": "Schedule default 2",
"day": null,
"actions": [
    {"type":"fatigue", "turn": 0, "amount": 1, "name":"Sleep"},
    {"type":"fatigue", "turn": 1, "amount": 1, "name":"Sleep"},
    {"type":"fatigue", "turn": 2, "amount": 1, "name":"Sleep"},
    {"type":"fatigue", "turn": 3, "amount": 1, "name":"Sleep"},
    {"type":"fatigue", "turn": 4, "amount": 1, "name":"Sleep"},
    {"type":"fatigue", "turn": 5, "amount": 1, "name":"Sleep"},
    {"type":"fatigue", "turn": 6, "amount": 1, "name":"Sleep"},
    {"type":"fatigue", "turn": 7, "amount": 1, "name":"Sleep"},
    {"type":"fatigue", "turn": 8, "amount": 1, "name":"Sleep"},
    {"type":"work", "turn": 9, "amount": 1, "name":"Work"},
    {"type":"work", "turn": 10, "amount": 1, "name":"Work"},
    {"type":"calories", "turn": 11, "amount": 1, "name":"Eat"},
    {"type":"work", "turn": 12, "amount": 1, "name":"Work"},
    {"type":"work", "turn": 13, "amount": 1, "name":"Work"},
    {"type":"calories", "turn": 14, "amount": 1, "name":"Eat"},
    {"type":"work", "turn": 15, "amount": 1, "name":"Work"},
    {"type":"work", "turn": 16, "amount": 1, "name":"Work"},
    {"type":"training", "turn": 17, "amount": 1, "name":"Training"},
    {"type":"training", "turn": 18, "amount": 1, "name":"Training"},   
    {"type":"training", "turn": 19, "amount": 1, "name":"Training"},
    {"type":"calories", "turn": 20, "amount": 1, "name":"Eat"}, 
    {"type":"training", "turn": 21, "amount": 1, "name":"Training"},   
    {"type":"training", "turn": 22, "amount": 1, "name":"Training"},
    {"type":"training", "turn": 23, "amount": 1, "name":"Training"},                  
]

}
